---
title: "Use sample database dump to test drive `MetaEgress`"
output: md_document
---

Last updated: `r format(Sys.time(), '%d %B, %Y')`

## About this sample database

This sample instance of LTER-core-metabase is a copy of the production database at [BLE-LTER](https://ble.lternet.edu). The backup is made without any access or GRANT statements, and does not specify ownership to any user/group role. As a test database, security is not a priority. The user you use to create the new database will effectively become the owner; use these credentials for `MetaEgress` later on.

## Download database backup script

[Download here.](../../sample_metabase/sample_metabase_dump.sql)

The backup is in plain text .sql format. You might wish to inspect it in a text editor.

## Create new database and restore schema + data

1. Using the command line program psql

```{}
psql CREATE DATABASE metabase;      -- create new empty database called "metabase"

psql \c metabase;                   -- switch to the new database

psql \i <path to plain-text backup> -- execute backup script on new database
```

2. You can also use pgAdmin or DBeaver to create a new database and then "execute" this SQL dump on the new database to apply the schema and populate example entries.